INSERT INTO tb_users (name) VALUES ('João');
INSERT INTO tb_users (name) VALUES ('Maria');
INSERT INTO tb_users (name) VALUES ('Zeca');
INSERT INTO tb_users (name) VALUES ('Mario');
INSERT INTO tb_users (name) VALUES ('Gustavo');
INSERT INTO tb_users (name) VALUES ('Camila');
INSERT INTO tb_users (name) VALUES ('Pedro');
INSERT INTO tb_users (name) VALUES ('Juliana');
INSERT INTO tb_users (name) VALUES ('Gisele');